export const API = {
  courses: "/courses",
  courseById: "/courses/",
  applyCourse: "/courses/",
  partners: "/partners",
  teachers: "/teachers",
  projectsPast: "/projects/past",
  projectsFuture: "/projects/future",
  blog: "/blog",
  blogId: "/blog/:id",
  contact: "/contact",
  career: "/career/apply",
  events: "/events",
  scholarships: "/scholarships",
  carousel: "/carousel",
  past: "/hackathons/past",
  future: "/hackathons/future",
  registerHakaton: "/hackathons/",
};
